handlers=de.amklee.monomovie.util.StdoutConsoleHandler
de.amklee.monomovie.util.StdoutConsoleHandler.level=INFO
de.amklee.monomovie.util.StdoutConsoleHandler.formatter=de.amklee.monomovie.util.ColorConsoleFormatter
