# Use `gradle versionCatalogUpdate` task to update these
[versions]
closure-compiler = "v20260831"
foojay-resolver-convention = "1.0.0"
gradle-shadow = "9.6.1"
jellyfin = "1.8.12"
jlink-runtime = "2.0.1"
kotlin = "2.4.10"
kotlinpoet = "2.3.0"
kotlinx-html = "0.12.0-jf.3"
ktlint = "1.8.0"
ktor = "3.5.2"
slf4j = "2.0.18"
version-catalog-update = "1.1.1"

[libraries]
closure-compiler = { module = "com.google.javascript:closure-compiler", version.ref = "closure-compiler" }
jellyfin-core = { module = "org.jellyfin.sdk:jellyfin-core", version.ref = "jellyfin" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html", version.ref = "kotlinx-html" }
ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint" }
ktor-version-catalog = { module = "io.ktor:ktor-version-catalog", version.ref = "ktor" }
slf4j-jdk14 = { module = "org.slf4j:slf4j-jdk14", version.ref = "slf4j" }

[plugins]
foojay-resolver-convention = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay-resolver-convention" }
jlink-runtime = { id = "org.beryx.runtime", version.ref = "jlink-runtime" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "gradle-shadow" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
