CREATE TABLE IF NOT EXISTS BOOKMARKS (ID VARCHAR(255) PRIMARY KEY, BOOKMARKED_AT BIGINT NOT NULL, IS_BOOKMARKED BOOLEAN DEFAULT TRUE NOT NULL, COLOUR VARCHAR(63) NULL);
CREATE TABLE IF NOT EXISTS WATCHED (ID VARCHAR(255) PRIMARY KEY, WATCHED_AT BIGINT NOT NULL, CONSTRAINT FK_WATCHED_ID__ID FOREIGN KEY (ID) REFERENCES BOOKMARKS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS MIGRATIONS (ID BIGINT AUTO_INCREMENT PRIMARY KEY, "name" VARCHAR(255) NOT NULL, HASH VARCHAR(255) NOT NULL);
